[package]
name = "tama-core"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = { workspace = true }
heapless = "0.9.1"
rand = { version = "0.9.2", default-features = false, features = ["small_rng"] }
